<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="0" name="WDPA_Test" tests="6" failures="1" timestamp="10 Apr 2019 17:53:14 GMT" time="171.113" errors="0">
  <testcase name="SetEvironmentLevel" time="0.035" classname="SupportClasses.Environment">
    <skipped/>
  </testcase> <!-- SetEvironmentLevel -->
  <testcase name="Pickup_LTLFreight_Anonymous" time="42.021" classname="WDPA_Application.WDPA_SmokeTest"/>
  <testcase name="Pickup_Express" time="131.331" classname="WDPA_Application.WDPA_SmokeTest"/>
  <testcase name="Pickup_ExpressFreight" time="135.91" classname="WDPA_Application.WDPA_SmokeTest"/>
  <testcase name="Pickup_LTLFreight" time="154.589" classname="WDPA_Application.WDPA_SmokeTest"/>
  <testcase name="Pickup_Ground" time="168.661" classname="WDPA_Application.WDPA_SmokeTest">
    <failure type="java.lang.AssertionError" message="The system has experienced an unexpected problem and is unable to complete your request. Please contact FedEx Customer Service to schedule your pickup.">
      <![CDATA[java.lang.AssertionError: The system has experienced an unexpected problem and is unable to complete your request. Please contact FedEx Customer Service to schedule your pickup.
at WDPA_Application.WDPA_SmokeTest.Pickup_Ground(WDPA_SmokeTest.java:96)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- Pickup_Ground -->
</testsuite> <!-- WDPA_Test -->
