<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="3" name="Default test" tests="21" failures="7" timestamp="19 Jun 2019 20:36:33 GMT" time="57.418" errors="0">
  <testcase name="CheckLogin" time="2.177" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckLogin(USRC_TestData_Update.java:189)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckLogin -->
  <testcase name="CheckLogin" time="2.483" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckLogin(USRC_TestData_Update.java:189)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckLogin -->
  <testcase name="CheckLogin" time="2.965" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckLogin(USRC_TestData_Update.java:189)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckLogin -->
  <testcase name="CheckLogin" time="3.294" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckLogin(USRC_TestData_Update.java:189)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckLogin -->
  <testcase name="CheckLogin" time="3.532" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckLogin(USRC_TestData_Update.java:189)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckLogin -->
  <testcase name="CheckLogin" time="3.779" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckLogin(USRC_TestData_Update.java:189)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckLogin -->
  <testcase name="CheckLogin" time="4.106" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckLogin(USRC_TestData_Update.java:189)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckLogin -->
  <testcase name="CheckLogin" time="11.258" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="28.224" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="27.994" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="27.9" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="27.85" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="31.566" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="36.467" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="36.676" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="36.551" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="35.567" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="31.899" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="23.49" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="24.534" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="24.501" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckMigration" time="0.0" classname="USRC_Application.USRC_TestData_Update">
    <ignored/>
  </testcase> <!-- CheckMigration -->
  <testcase name="Check_WCRV_Status" time="0.0" classname="USRC_Application.USRC_TestData_Update">
    <ignored/>
  </testcase> <!-- Check_WCRV_Status -->
  <testcase name="UpdateUser" time="0.0" classname="USRC_Application.USRC_TestData_Update">
    <ignored/>
  </testcase> <!-- UpdateUser -->
</testsuite> <!-- Default test -->
