<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="1" name="Default test" tests="1" failures="1" timestamp="19 Jun 2019 15:07:04 GMT" time="7.716" errors="0">
  <testcase name="EndtoEndEnrollment" time="6.18" classname="USRC_Application.USRC_FDM">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;enrollmentOptionsList&amp;quot;
     but: was &amp;quot;{
    &amp;quot;error&amp;quot;: &amp;quot;invalid_request&amp;quot;,
    &amp;quot;error_description&amp;quot;: &amp;quot;validation error&amp;quot;
}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "enrollmentOptionsList"
     but: was "{
    "error": "invalid_request",
    "error_description": "validation error"
}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_FDM.EndtoEndEnrollment(USRC_FDM.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- EndtoEndEnrollment -->
  <testcase name="EndtoEndEnrollment_UserID" time="0.0" classname="USRC_Application.USRC_FDM">
    <ignored/>
  </testcase> <!-- EndtoEndEnrollment_UserID -->
</testsuite> <!-- Default test -->
