<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="WDPA_Application.WDPA_SmokeTest" tests="1" failures="1" timestamp="31 May 2019 00:28:05 GMT" time="187.064" errors="0">
  <testcase name="WDPA_LTLFreight" time="187.064" classname="WDPA_Application.WDPA_SmokeTest">
    <failure type="java.lang.AssertionError" message="Text still present.  By.id: freightPickupInfo.readyTime - ">
      <![CDATA[java.lang.AssertionError: Text still present.  By.id: freightPickupInfo.readyTime - 
at org.testng.Assert.fail(Assert.java:96)
at WDPA_Application.WDPA_SmokeTest.WDPA_LTLFreight(WDPA_SmokeTest.java:129)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- WDPA_LTLFreight -->
</testsuite> <!-- WDPA_Application.WDPA_SmokeTest -->
