<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="WFCL_Application.WFCL_SmokeTest" tests="1" failures="1" timestamp="18 Jun 2019 20:46:58 GMT" time="4370.424" errors="0">
  <testcase name="WFCL_CreditCardRegistration" time="4370.424" classname="WFCL_Application.WFCL_SmokeTest">
    <failure type="java.lang.AssertionError" message="User is still on the credit card entry page">
      <![CDATA[java.lang.AssertionError: User is still on the credit card entry page
at org.testng.Assert.fail(Assert.java:96)
at WFCL_Application.WFCL_SmokeTest.WFCL_CreditCardRegistration(WFCL_SmokeTest.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- WFCL_CreditCardRegistration -->
</testsuite> <!-- WFCL_Application.WFCL_SmokeTest -->
