<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="ADAT_Application.ADAT" tests="14" failures="8" timestamp="23 Apr 2019 18:39:17 GMT" time="2.964" errors="0">
  <testcase name="ADAT_CreateUser" time="0.408" classname="ADAT_Application.ADAT"/>
  <testcase name="ADAT_CreateUser" time="0.404" classname="ADAT_Application.ADAT"/>
  <testcase name="ADAT_CreatePin" time="0.198" classname="ADAT_Application.ADAT"/>
  <testcase name="ADAT_CreatePin" time="0.166" classname="ADAT_Application.ADAT"/>
  <testcase name="ADAT_PostcardVelocity" time="0.150" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;&lt;rf11:advice&gt;&quot;
     but: was &quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_PostcardVelocity(ADAT.java:105)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ADAT_PostcardVelocity -->
  <testcase name="ADAT_PhoneVelocity" time="0.157" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;&lt;rf11:advice&gt;&quot;
     but: was &quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_PhoneVelocity(ADAT.java:114)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ADAT_PhoneVelocity -->
  <testcase name="ADAT_AddressVelocity" time="0.172" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;&lt;rf11:advice&gt;&quot;
     but: was &quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_AddressVelocity(ADAT.java:96)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ADAT_AddressVelocity -->
  <testcase name="ADAT_PostcardVelocity" time="0.157" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;&lt;rf11:advice&gt;&quot;
     but: was &quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_PostcardVelocity(ADAT.java:105)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ADAT_PostcardVelocity -->
  <testcase name="ADAT_AddressVelocity" time="0.089" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;&lt;rf11:advice&gt;&quot;
     but: was &quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_AddressVelocity(ADAT.java:96)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ADAT_AddressVelocity -->
  <testcase name="ADAT_PhoneVelocity" time="0.075" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;&lt;rf11:advice&gt;&quot;
     but: was &quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_PhoneVelocity(ADAT.java:114)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ADAT_PhoneVelocity -->
  <testcase name="ADAT_VerifyPin_Invalid" time="0.214" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;400Bad&quot;
     but: was &quot;&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;SOAP-ENV:Envelope xmlns:SOAP-ENV=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:SOAP-ENC=&quot;http://www.w3.org/2003/05/soap-encoding&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:cx=&quot;http://ws.arcot.com/WebFortCommonAPI/7.0/xsd&quot; xmlns:wfiss60msgs=&quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/msgs&quot; xmlns:wfiss60xsd=&quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/xsd&quot; xmlns:wfiss60soap11=&quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP11Binding&quot; xmlns:wfiss60soap12=&quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP12Binding&quot; xmlns:wfauth60msgs=&quot;http://ws.arcot.com/WebFortAuthAPI/7.0/msgs&quot; xmlns:wfauth60xsd=&quot;http://ws.arcot.com/WebFortAuthAPI/7.0/xsd&quot; xmlns:wfauth60soap11=&quot;http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP11Binding&quot; xmlns:wfauth60soap12=&quot;http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP12Binding&quot; xmlns:wfauth50soap11=&quot;http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP11Binding&quot; xmlns:wfauth50types=&quot;http://schemas.arcot.com/webfort/v1/types&quot; xmlns:wfauth50soap12=&quot;http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP12Binding&quot; xmlns:wfautha541soap11=&quot;http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP11Binding&quot; xmlns:wfautha541soap12=&quot;http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP12Binding&quot; xmlns:wfauthx541soap11=&quot;http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP11Binding&quot; xmlns:wfauth541types=&quot;http://schemas.arcot.com/webfort/v2/types&quot; xmlns:wfauthx541soap12=&quot;http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP12Binding&quot; xmlns:wfiss50soap11=&quot;http://schemas.arcot.com/regfort/v1/RegFortAPISOAP11Binding&quot; xmlns:wfiss50types=&quot;http://schemas.arcot.com/regfort/v1/types&quot; xmlns:wfiss50soap12=&quot;http://schemas.arcot.com/regfort/v1/RegFortAPISOAP12Binding&quot; xmlns:wfiss541soap11=&quot;http://schemas.arcot.com/regfort/v2/RegFortAPISOAP11Binding&quot; xmlns:wfiss541types=&quot;http://schemas.arcot.com/regfort/v2/types&quot; xmlns:wfiss541soap12=&quot;http://schemas.arcot.com/regfort/v2/RegFortAPISOAP12Binding&quot;&gt;&lt;SOAP-ENV:Header&gt;&lt;/SOAP-ENV:Header&gt;&lt;SOAP-ENV:Body&gt;&lt;SOAP-ENV:Fault&gt;&lt;SOAP-ENV:Code&gt;&lt;SOAP-ENV:Value&gt;SOAP-ENV:Sender&lt;/SOAP-ENV:Value&gt;&lt;/SOAP-ENV:Code&gt;&lt;SOAP-ENV:Reason&gt;&lt;SOAP-ENV:Text xml:lang=&quot;en&quot;&gt;WebFortAuthFault&lt;/SOAP-ENV:Text&gt;&lt;/SOAP-ENV:Reason&gt;&lt;SOAP-ENV:Detail&gt;&lt;wfauth60msgs:WebFortAuthFault&gt;&lt;cx:message&gt;The provided authentication credentials are not correct.&lt;/cx:message&gt;&lt;cx:reasonCode&gt;0&lt;/cx:reasonCode&gt;&lt;cx:responseCode&gt;5707&lt;/cx:responseCode&gt;&lt;cx:transactionID&gt;37358031&lt;/cx:transactionID&gt;&lt;cx:additionalOutput&gt;&lt;/cx:additionalOutput&gt;&lt;wfauth60msgs:credType&gt;4&lt;/wfauth60msgs:credType&gt;&lt;/wfauth60msgs:WebFortAuthFault&gt;&lt;/SOAP-ENV:Detail&gt;&lt;/SOAP-ENV:Fault&gt;&lt;/SOAP-ENV:Body&gt;&lt;/SOAP-ENV:Envelope&gt;
&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "400Bad"
     but: was "<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cx="http://ws.arcot.com/WebFortCommonAPI/7.0/xsd" xmlns:wfiss60msgs="http://ws.arcot.com/WebFortIssuanceAPI/6.0/msgs" xmlns:wfiss60xsd="http://ws.arcot.com/WebFortIssuanceAPI/6.0/xsd" xmlns:wfiss60soap11="http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP11Binding" xmlns:wfiss60soap12="http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP12Binding" xmlns:wfauth60msgs="http://ws.arcot.com/WebFortAuthAPI/7.0/msgs" xmlns:wfauth60xsd="http://ws.arcot.com/WebFortAuthAPI/7.0/xsd" xmlns:wfauth60soap11="http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP11Binding" xmlns:wfauth60soap12="http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP12Binding" xmlns:wfauth50soap11="http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP11Binding" xmlns:wfauth50types="http://schemas.arcot.com/webfort/v1/types" xmlns:wfauth50soap12="http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP12Binding" xmlns:wfautha541soap11="http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP11Binding" xmlns:wfautha541soap12="http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP12Binding" xmlns:wfauthx541soap11="http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP11Binding" xmlns:wfauth541types="http://schemas.arcot.com/webfort/v2/types" xmlns:wfauthx541soap12="http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP12Binding" xmlns:wfiss50soap11="http://schemas.arcot.com/regfort/v1/RegFortAPISOAP11Binding" xmlns:wfiss50types="http://schemas.arcot.com/regfort/v1/types" xmlns:wfiss50soap12="http://schemas.arcot.com/regfort/v1/RegFortAPISOAP12Binding" xmlns:wfiss541soap11="http://schemas.arcot.com/regfort/v2/RegFortAPISOAP11Binding" xmlns:wfiss541types="http://schemas.arcot.com/regfort/v2/types" xmlns:wfiss541soap12="http://schemas.arcot.com/regfort/v2/RegFortAPISOAP12Binding"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><SOAP-ENV:Fault><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Sender</SOAP-ENV:Value></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="en">WebFortAuthFault</SOAP-ENV:Text></SOAP-ENV:Reason><SOAP-ENV:Detail><wfauth60msgs:WebFortAuthFault><cx:message>The provided authentication credentials are not correct.</cx:message><cx:reasonCode>0</cx:reasonCode><cx:responseCode>5707</cx:responseCode><cx:transactionID>37358031</cx:transactionID><cx:additionalOutput></cx:additionalOutput><wfauth60msgs:credType>4</wfauth60msgs:credType></wfauth60msgs:WebFortAuthFault></SOAP-ENV:Detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT.ADAT_VerifyPin_Invalid(ADAT.java:149)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ADAT_VerifyPin_Invalid -->
  <testcase name="ADAT_VerifyPin" time="0.264" classname="ADAT_Application.ADAT"/>
  <testcase name="ADAT_VerifyPin" time="0.301" classname="ADAT_Application.ADAT"/>
  <testcase name="ADAT_VerifyPin_Invalid" time="0.209" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;400Bad&quot;
     but: was &quot;&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;SOAP-ENV:Envelope xmlns:SOAP-ENV=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:SOAP-ENC=&quot;http://www.w3.org/2003/05/soap-encoding&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:cx=&quot;http://ws.arcot.com/WebFortCommonAPI/7.0/xsd&quot; xmlns:wfiss60msgs=&quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/msgs&quot; xmlns:wfiss60xsd=&quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/xsd&quot; xmlns:wfiss60soap11=&quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP11Binding&quot; xmlns:wfiss60soap12=&quot;http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP12Binding&quot; xmlns:wfauth60msgs=&quot;http://ws.arcot.com/WebFortAuthAPI/7.0/msgs&quot; xmlns:wfauth60xsd=&quot;http://ws.arcot.com/WebFortAuthAPI/7.0/xsd&quot; xmlns:wfauth60soap11=&quot;http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP11Binding&quot; xmlns:wfauth60soap12=&quot;http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP12Binding&quot; xmlns:wfauth50soap11=&quot;http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP11Binding&quot; xmlns:wfauth50types=&quot;http://schemas.arcot.com/webfort/v1/types&quot; xmlns:wfauth50soap12=&quot;http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP12Binding&quot; xmlns:wfautha541soap11=&quot;http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP11Binding&quot; xmlns:wfautha541soap12=&quot;http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP12Binding&quot; xmlns:wfauthx541soap11=&quot;http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP11Binding&quot; xmlns:wfauth541types=&quot;http://schemas.arcot.com/webfort/v2/types&quot; xmlns:wfauthx541soap12=&quot;http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP12Binding&quot; xmlns:wfiss50soap11=&quot;http://schemas.arcot.com/regfort/v1/RegFortAPISOAP11Binding&quot; xmlns:wfiss50types=&quot;http://schemas.arcot.com/regfort/v1/types&quot; xmlns:wfiss50soap12=&quot;http://schemas.arcot.com/regfort/v1/RegFortAPISOAP12Binding&quot; xmlns:wfiss541soap11=&quot;http://schemas.arcot.com/regfort/v2/RegFortAPISOAP11Binding&quot; xmlns:wfiss541types=&quot;http://schemas.arcot.com/regfort/v2/types&quot; xmlns:wfiss541soap12=&quot;http://schemas.arcot.com/regfort/v2/RegFortAPISOAP12Binding&quot;&gt;&lt;SOAP-ENV:Header&gt;&lt;/SOAP-ENV:Header&gt;&lt;SOAP-ENV:Body&gt;&lt;SOAP-ENV:Fault&gt;&lt;SOAP-ENV:Code&gt;&lt;SOAP-ENV:Value&gt;SOAP-ENV:Sender&lt;/SOAP-ENV:Value&gt;&lt;/SOAP-ENV:Code&gt;&lt;SOAP-ENV:Reason&gt;&lt;SOAP-ENV:Text xml:lang=&quot;en&quot;&gt;WebFortAuthFault&lt;/SOAP-ENV:Text&gt;&lt;/SOAP-ENV:Reason&gt;&lt;SOAP-ENV:Detail&gt;&lt;wfauth60msgs:WebFortAuthFault&gt;&lt;cx:message&gt;The provided authentication credentials are not correct.&lt;/cx:message&gt;&lt;cx:reasonCode&gt;0&lt;/cx:reasonCode&gt;&lt;cx:responseCode&gt;5707&lt;/cx:responseCode&gt;&lt;cx:transactionID&gt;37358032&lt;/cx:transactionID&gt;&lt;cx:additionalOutput&gt;&lt;/cx:additionalOutput&gt;&lt;wfauth60msgs:credType&gt;4&lt;/wfauth60msgs:credType&gt;&lt;/wfauth60msgs:WebFortAuthFault&gt;&lt;/SOAP-ENV:Detail&gt;&lt;/SOAP-ENV:Fault&gt;&lt;/SOAP-ENV:Body&gt;&lt;/SOAP-ENV:Envelope&gt;
&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "400Bad"
     but: was "<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cx="http://ws.arcot.com/WebFortCommonAPI/7.0/xsd" xmlns:wfiss60msgs="http://ws.arcot.com/WebFortIssuanceAPI/6.0/msgs" xmlns:wfiss60xsd="http://ws.arcot.com/WebFortIssuanceAPI/6.0/xsd" xmlns:wfiss60soap11="http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP11Binding" xmlns:wfiss60soap12="http://ws.arcot.com/WebFortIssuanceAPI/6.0/wsdl/IssuanceAPISOAP12Binding" xmlns:wfauth60msgs="http://ws.arcot.com/WebFortAuthAPI/7.0/msgs" xmlns:wfauth60xsd="http://ws.arcot.com/WebFortAuthAPI/7.0/xsd" xmlns:wfauth60soap11="http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP11Binding" xmlns:wfauth60soap12="http://ws.arcot.com/WebFortAuthAPI/6.0/wsdl/AuthAPISOAP12Binding" xmlns:wfauth50soap11="http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP11Binding" xmlns:wfauth50types="http://schemas.arcot.com/webfort/v1/types" xmlns:wfauth50soap12="http://schemas.arcot.com/webfort/v1/ArcotWebFortWebServiceSOAP12Binding" xmlns:wfautha541soap11="http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP11Binding" xmlns:wfautha541soap12="http://schemas.arcot.com/webfort/v2/AuthAccessorServiceSOAP12Binding" xmlns:wfauthx541soap11="http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP11Binding" xmlns:wfauth541types="http://schemas.arcot.com/webfort/v2/types" xmlns:wfauthx541soap12="http://schemas.arcot.com/webfort/v2/AuthXActionServiceSOAP12Binding" xmlns:wfiss50soap11="http://schemas.arcot.com/regfort/v1/RegFortAPISOAP11Binding" xmlns:wfiss50types="http://schemas.arcot.com/regfort/v1/types" xmlns:wfiss50soap12="http://schemas.arcot.com/regfort/v1/RegFortAPISOAP12Binding" xmlns:wfiss541soap11="http://schemas.arcot.com/regfort/v2/RegFortAPISOAP11Binding" xmlns:wfiss541types="http://schemas.arcot.com/regfort/v2/types" xmlns:wfiss541soap12="http://schemas.arcot.com/regfort/v2/RegFortAPISOAP12Binding"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><SOAP-ENV:Fault><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Sender</SOAP-ENV:Value></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="en">WebFortAuthFault</SOAP-ENV:Text></SOAP-ENV:Reason><SOAP-ENV:Detail><wfauth60msgs:WebFortAuthFault><cx:message>The provided authentication credentials are not correct.</cx:message><cx:reasonCode>0</cx:reasonCode><cx:responseCode>5707</cx:responseCode><cx:transactionID>37358032</cx:transactionID><cx:additionalOutput></cx:additionalOutput><wfauth60msgs:credType>4</wfauth60msgs:credType></wfauth60msgs:WebFortAuthFault></SOAP-ENV:Detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT.ADAT_VerifyPin_Invalid(ADAT.java:149)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ADAT_VerifyPin_Invalid -->
</testsuite> <!-- ADAT_Application.ADAT -->
