<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="Soap_Execution.ADAT" tests="14" failures="1" timestamp="17 Feb 2019 06:09:12 GMT" time="37.391" errors="0">
  <testcase name="ADAT_CreateUser" time="0.655" classname="Soap_Execution.ADAT"/>
  <testcase name="ADAT_CreateUser" time="0.740" classname="Soap_Execution.ADAT"/>
  <testcase name="ADAT_CreatePin" time="0.348" classname="Soap_Execution.ADAT"/>
  <testcase name="ADAT_CreatePin" time="0.932" classname="Soap_Execution.ADAT"/>
  <testcase name="ADAT_PostcardVelocity" time="1.309" classname="Soap_Execution.ADAT"/>
  <testcase name="ADAT_AddressVelocity" time="3.635" classname="Soap_Execution.ADAT"/>
  <testcase name="ADAT_AddressVelocity" time="12.391" classname="Soap_Execution.ADAT"/>
  <testcase name="ADAT_PhoneVelocity" time="5.316" classname="Soap_Execution.ADAT"/>
  <testcase name="ADAT_PostcardVelocity" time="5.700" classname="Soap_Execution.ADAT"/>
  <testcase name="ADAT_PhoneVelocity" time="1.447" classname="Soap_Execution.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;&lt;rf11:advice&gt;&quot;
     but: was &quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Bad response: (400Bad Request&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Bad response: (400Bad Request"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at Soap_Execution.ADAT.ADAT_EvaluateRisk(ADAT.java:303)
at Soap_Execution.ADAT.VelocityCheck(ADAT.java:140)
at Soap_Execution.ADAT.ADAT_PhoneVelocity(ADAT.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ADAT_PhoneVelocity -->
  <testcase name="ADAT_VerifyPin" time="1.711" classname="Soap_Execution.ADAT"/>
  <testcase name="ADAT_VerifyPin_Invalid" time="0.753" classname="Soap_Execution.ADAT"/>
  <testcase name="ADAT_VerifyPin" time="0.752" classname="Soap_Execution.ADAT"/>
  <testcase name="ADAT_VerifyPin_Invalid" time="1.702" classname="Soap_Execution.ADAT"/>
</testsuite> <!-- Soap_Execution.ADAT -->
